blank_issues_enabled: false
contact_links:
  - name: Support Question
    url: https://spomky-labs.com/contact/
    about: We use GitHub issues only to discuss about bugs and new features. For this kind of questions about using the library, please use Stackoverflow (or similar) or send a quote request at https://spomky-labs.com/contact/
