# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Integrate"

on:
  push:
    branches:
      - "*.x"

jobs:
  mutation_testing:
    name: "5️⃣ Mutation Testing"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.3"
          extensions: "ctype, dom, json, libxml, mbstring, openssl, phar, simplexml, tokenizer, xml, xmlwriter"
          coverage: "xdebug"

      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Fetch Git base reference"
        run: "git fetch --depth=1 origin ${GITHUB_BASE_REF}"

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"
          composer-options: "--optimize-autoloader"

      - name: "Execute Infection"
        run: "make ci-mu"
